import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it, vi } from "vitest";
import { and, eq, inArray } from "drizzle-orm";
import { applications, applicationStageHistory, candidates, clientOffers, clients, db, jobs, jobStages, organization, user } from "@harly/db";
const mocks = vi.hoisted(() => ({ context: vi.fn() }));
vi.mock("next/cache", () => ({ revalidatePath: vi.fn() }));
vi.mock("@/features/workspaces/context", () => ({ getWorkspaceContext: mocks.context }));
vi.mock("@/server/events/emit", () => ({ persistDomainEvent: vi.fn().mockResolvedValue({ eventId: "test-event" }), publishPersistedDomainEvents: vi.fn() }));
vi.mock("@/server/webhooks/emit", () => ({ emitWebhookEvent: vi.fn() }));
vi.mock("@/lib/email/outbox-processor", () => ({ enqueueEmailOutbox: vi.fn(), processEmailOutbox: vi.fn() }));
import { saveClient, archiveClient, linkJobClient } from "./actions";
import { recordClientOffer, getAgencyApplication } from "./application-actions";
import { updateApplicationStatus, bulkMoveApplications } from "@/features/pipeline/actions";
import { moveApplicationStageForApi } from "@/features/applications/service";
import { getHiringEvents } from "@/features/reports/data";
import { getOfferDecisionTotals } from "@/features/reports/offer-decisions";
import { withoutEvaluationGuidance } from "@/features/jobs/public-job";
import { getPipelineData } from "@/features/pipeline/data";
import { getPipelineOverview } from "@/features/dashboard/widgets";
import { enqueueEmailOutbox } from "@/lib/email/outbox-processor";

const integration = process.env.RUN_AGENCY_INTEGRATION === "1" ? describe : describe.skip;
integration("agency workflow", () => {
  const workspaceId = `agency-${randomUUID()}`, otherWorkspaceId = `agency-${randomUUID()}`, userId = randomUUID();
  const jobId = randomUUID(), candidateId = randomUUID(), applicationId = randomUUID(), stageId = randomUUID(), hiredId = randomUUID(), otherClientId = randomUUID(), rejectedId = randomUUID(), clientRejectedId = randomUUID();
  let clientId = "";
  beforeAll(async () => {
    const url = new URL(process.env.DATABASE_URL!);
    if (!["localhost", "127.0.0.1"].includes(url.hostname) || url.pathname !== "/harly_talmore_eval") throw new Error("Use local evaluation database");
    await db.insert(organization).values([workspaceId, otherWorkspaceId].map((id) => ({ id, slug: id, name: "Fictional agency", createdAt: new Date() })));
    await db.insert(user).values({ id: userId, email: `${userId}@example.test`, name: "Fictional recruiter" });
    await db.insert(jobs).values({ id: jobId, workspaceId, createdById: userId, title: "Fictional role", slug: jobId, employmentType: "full_time", workplaceType: "onsite", description: "Fixture", status: "open" });
    await db.insert(jobStages).values([{ id: stageId, name: "Submitted", order: 0 }, { id: hiredId, name: "Hired", order: 1 }, { id: rejectedId, name: "Rejected", order: 2 }, { id: clientRejectedId, name: "Rejected by client", order: 3 }].map((stage) => ({ ...stage, jobId, workspaceId })));
    await db.insert(candidates).values({ id: candidateId, workspaceId, firstName: "Fictional", lastName: "Candidate", email: `${candidateId}@example.test` });
    await db.insert(applications).values({ id: applicationId, jobId, workspaceId, candidateId, currentStageId: stageId });
    await db.insert(clients).values({ id: otherClientId, workspaceId: otherWorkspaceId, name: "Other workspace" });
    mocks.context.mockResolvedValue({ organization: { id: workspaceId }, user: { id: userId }, roleKey: "owner" });
  });
  afterAll(async () => {
    await db.delete(jobs).where(eq(jobs.id, jobId));
    await db.delete(organization).where(inArray(organization.id, [workspaceId, otherWorkspaceId]));
    await db.delete(user).where(eq(user.id, userId));
  });
  it("creates an internal client, links a job and prevents cross-workspace links", async () => {
    const saved = await saveClient({ name: "Fictional company", website: "https://example.test", notes: "Internal", contacts: [{ name: "Fictional contact", email: "client@example.test", phone: "", role: "Recruiting" }] });
    expect(saved.success).toBe(true); if (!saved.success) throw new Error("Save failed"); clientId = saved.id;
    expect((await linkJobClient(jobId, clientId)).success).toBe(true);
    expect((await linkJobClient(jobId, otherClientId)).success).toBe(false);
    const [job] = await db.select().from(jobs).where(eq(jobs.id, jobId));
    expect(job.clientId).toBe(clientId);
    const pipeline = await getPipelineData("all", clientId);
    expect(pipeline.kind === "ready" && pipeline.applications.map((row) => row.clientName)).toEqual(["Fictional company"]);
    const otherPipeline = await getPipelineData("all", otherClientId);
    expect(otherPipeline.kind === "ready" && otherPipeline.applications.length).toBe(0);
    expect(withoutEvaluationGuidance(job)).not.toHaveProperty("clientId");
    expect((await saveClient({ id: otherClientId, name: "Changed", contacts: [] })).success).toBe(false);
  });
  it("records client offers without sending or hiring; decisions drive acceptance reporting", async () => {
    expect((await recordClientOffer({ applicationId, offeredOn: "2026-09-18", status: "accepted", terms: "Terms unknown" })).success).toBe(true);
    expect((await recordClientOffer({ applicationId, offeredOn: "2026-02-30", status: "pending", terms: "" })).success).toBe(false);
    const data = await getAgencyApplication(applicationId);
    expect(data.status).toBe("active"); expect(data.offers).toHaveLength(1);
    expect(await getOfferDecisionTotals(workspaceId)).toEqual([{ accepted: 1, decided: 1 }]);
    expect(enqueueEmailOutbox).not.toHaveBeenCalled();
    expect((await recordClientOffer({ id: data.offers[0].id, applicationId, offeredOn: "2026-09-18", status: "declined", terms: "" })).success).toBe(true);
    expect(await getOfferDecisionTotals(workspaceId)).toEqual([{ accepted: 0, decided: 1 }]);
  });
  it("hires without an accepted offer and records a backdated hire date atomically", async () => {
    const input = { applicationIds: [applicationId], workspaceId, status: "hired" as const, hireDetails: { hiredOn: "2026-09-17", hireTerms: "Start date to be confirmed" } };
    expect(await updateApplicationStatus(input)).toEqual({ success: true });
    const data = await getAgencyApplication(applicationId);
    expect(data.status).toBe("hired"); expect(data.hiredOn).toBe("2026-09-17");
    expect(data.hireTerms).toBe("Start date to be confirmed");
    expect((await getPipelineOverview(jobId)).stages.find((stage) => stage.name === "Hired")?.count).toBe(1);
    expect((await getHiringEvents(workspaceId)).map((event) => new Date(event.hiredAt).toISOString().slice(0, 10))).toEqual(["2026-09-17"]);
    expect(await getHiringEvents(workspaceId, { since: new Date("2026-09-18T00:00:00Z") })).toHaveLength(0);
    expect(await updateApplicationStatus({ ...input, hireDetails: { ...input.hireDetails, hireTerms: "Updated terms" } })).toEqual({ success: true });
    expect(await db.select().from(applicationStageHistory).where(and(eq(applicationStageHistory.applicationId, applicationId), eq(applicationStageHistory.toStageId, hiredId)))).toHaveLength(1);
    expect(await getOfferDecisionTotals(workspaceId)).toEqual([{ accepted: 0, decided: 1 }]);
    expect(enqueueEmailOutbox).not.toHaveBeenCalled();
  });
  it("keeps client rejection terminal and preserves both rejection sources after reopening", async () => {
    expect((await updateApplicationStatus({ applicationIds: [applicationId], workspaceId, status: "active" })).success).toBe(true);
    expect((await bulkMoveApplications({ applicationIds: [applicationId], workspaceId, toStageId: clientRejectedId })).success).toBe(true);
    let [application] = await db.select().from(applications).where(eq(applications.id, applicationId));
    expect(application.status).toBe("rejected"); expect(application.rejectionSource).toBe("client");
    const pipeline = await getPipelineData("all");
    expect(pipeline.kind === "ready" && pipeline.applications.length).toBe(0);
    expect((await updateApplicationStatus({ applicationIds: [applicationId], workspaceId, status: "rejected" })).success).toBe(true);
    expect((await updateApplicationStatus({ applicationIds: [applicationId], workspaceId, status: "active" })).success).toBe(true);
    [application] = await db.select().from(applications).where(eq(applications.id, applicationId));
    expect(application.currentStageId).toBe(stageId); expect(application.rejectionSource).toBeNull();
    const history = await db.select().from(applicationStageHistory).where(eq(applicationStageHistory.applicationId, applicationId));
    expect(history.some((row) => row.rejectionSource === "client")).toBe(true);
    expect(history.some((row) => row.rejectionSource === "agency")).toBe(true);
    const apiResult = await moveApplicationStageForApi({ workspaceId, applicationId, toStageId: clientRejectedId, actorId: userId });
    expect(apiResult.status).toBe("rejected"); expect(apiResult.rejectionSource).toBe("client");
    const overview = await getPipelineOverview(jobId);
    expect(overview.stages.map((stage) => stage.name)).toEqual(["Submitted", "Hired", "Rejected", "Rejected by client"]);
    expect(overview.stages.find((stage) => stage.name === "Rejected by client")?.count).toBe(1);
    expect(overview.total).toBe(1);
    expect(enqueueEmailOutbox).not.toHaveBeenCalled();
  });
  it("archives without erasing existing links, and denies unauthorized mutations", async () => {
    expect((await archiveClient(clientId, true)).success).toBe(true);
    expect((await linkJobClient(jobId, clientId)).success).toBe(false);
    expect((await getAgencyApplication(applicationId)).clientId).toBe(clientId);
    mocks.context.mockResolvedValue({ organization: { id: workspaceId }, user: { id: userId }, roleKey: "hiring_manager" });
    expect((await saveClient({ name: "Forbidden", contacts: [] })).success).toBe(false);
    expect((await recordClientOffer({ applicationId, offeredOn: "2026-09-18", status: "pending", terms: "" })).success).toBe(false);
    expect((await updateApplicationStatus({ applicationIds: [applicationId], workspaceId, status: "hired", hireDetails: { hiredOn: "2026-09-18", hireTerms: "Forbidden" } })).success).toBe(false);
    expect(await db.select().from(clientOffers).where(eq(clientOffers.workspaceId, workspaceId))).toHaveLength(1);
  });
});
